# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false
r_build_args: '--no-build-vignettes'
r_check_args: '--as-cran --ignore-vignettes'
bioc_required: true
bioc_use_devel: true
r_packages:
  - devtools
before_install:
  - tlmgr install index
